const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const { execFile } = require("node:child_process");
const path = require("node:path");
const { CoreClient, Ledger } = require("../dist/test/core");
const { claudeUsage, codexUsage } = require("../dist/test/providerUsage");
const { Router, defaultBoard } = require("../dist/test/model");
const { SessionHost } = require("../dist/test/session");
const root = path.resolve(__dirname, "..");
const python = path.resolve(root, "../../.venv/Scripts/python.exe");
const wait = async fn => { for (let i = 0; i < 600; i++) { if (fn()) return; await new Promise(r => setTimeout(r, 50)); } throw new Error("Timed out"); };

test("core reads create nothing; records survive a new client and cumulative reports do not double count", async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "patchport-p0-")); t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const core = new CoreClient(python, path.join(root, "core"));
  assert.ok((await core.request("capabilities")).actions.includes("usage"));
  const ledger = new Ledger(core, path.join(dir, "storage"));
  const binding = await ledger.inspect(dir);
  assert.equal(binding.linked, false);
  assert.equal((await ledger.report(dir)).sessions.length, 0);
  await assert.rejects(fs.stat(binding.database));
  const node = { id: "node1", name: "Peer \ud55c\uae00", project: dir, provider: "claude" };
  await ledger.start(node);
  await ledger.record(node.id, "completed", { answer: "Unicode \ud55c\uae00 retained" }, "turn1", "event1");
  await ledger.record(node.id, "completed", { answer: "Unicode \ud55c\uae00 retained" }, "turn1", "event1");
  await ledger.record(node.id, "usage", { sequence: 1, metrics: { input_tokens: 10, cost_usd: 0.2 } });
  await ledger.record(node.id, "usage", { sequence: 2, metrics: { input_tokens: 20, cost_usd: 0.3 } });
  const reopened = new CoreClient(python, path.join(root, "core"));
  const report = await reopened.request("interactive.report", { database: binding.database, project: dir });
  assert.equal(report.summary.metrics.input_tokens.known_sum, 20);
  assert.equal(report.summary.metrics.cost_usd.known_sum, 0.3);
  assert.equal(report.events.filter(e => e.kind === "completed").length, 1);
  assert.equal(report.events.find(e => e.kind === "completed").data.answer, "Unicode \ud55c\uae00 retained");
  await ledger.end();
  assert.equal((await ledger.report(dir)).sessions[0].state, "UNCERTAIN");
});

test("provider usage deduplicates streamed messages and reads only the exact fresh Codex session", async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "patchport-usage-")); t.after(() => fs.rm(dir, { recursive: true, force: true }));
  const started = Date.now() - 1000, id = "11111111-1111-4111-8111-111111111111", transcript = path.join(dir, `${id}.jsonl`);
  const usage = { input_tokens: 10, output_tokens: 2, cache_read_input_tokens: 5, cache_creation_input_tokens: 1 };
  const message = { type: "assistant", sessionId: id, timestamp: new Date().toISOString(), message: { id: "m1", model: "fixture", usage } };
  await fs.writeFile(transcript, [message, message, { ...message, message: { ...message.message, usage: { ...usage, output_tokens: 3 } } }].map(JSON.stringify).join("\n"));
  const claude = await claudeUsage(transcript, id, started);
  assert.equal(claude.metrics.input_tokens, 16); assert.equal(claude.metrics.output_tokens, 3); assert.equal(claude.metrics.cost_usd, null);
  await assert.rejects(claudeUsage(transcript, "other", started));
  const date = new Date(started), day = path.join(dir, "sessions", String(date.getUTCFullYear()), String(date.getUTCMonth() + 1).padStart(2, "0"), String(date.getUTCDate()).padStart(2, "0"));
  await fs.mkdir(day, { recursive: true });
  const file = path.join(day, `rollout-now-${id}.jsonl`);
  const meta = { type: "session_meta", payload: { id, cwd: dir, timestamp: new Date(started).toISOString() } };
  const cumulative = { type: "event_msg", payload: { type: "token_count", info: { total_token_usage: { input_tokens: 100, output_tokens: 8, cached_input_tokens: 70 } } } };
  await fs.writeFile(file, [meta, cumulative, cumulative].map(JSON.stringify).join("\n"));
  const codex = await codexUsage(dir, id, dir, started);
  assert.equal(codex.metrics.input_tokens, 100); assert.equal(codex.metrics.cache_read_tokens, 70); assert.equal(codex.metrics.cost_usd, null);
  await fs.writeFile(file, [meta, cumulative, { ...cumulative, payload: { ...cumulative.payload, info: { total_token_usage: { input_tokens: 90 } } } }].map(JSON.stringify).join("\n"));
  await assert.rejects(codexUsage(dir, id, dir, started));
  await fs.writeFile(file, [ { ...meta, payload: { ...meta.payload, timestamp: "2020-01-01T00:00:00Z" } }, cumulative ].map(JSON.stringify).join("\n"));
  await assert.rejects(codexUsage(dir, id, dir, started));
});

test("real managed mock PTYs persist before delivery and stop on a database recording failure", { timeout: 60000 }, async t => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "patchport-pty-ledger-"));
  const core = new CoreClient(python, path.join(root, "core")), ledger = new Ledger(core, path.join(dir, "ledger"));
  const board = defaultBoard(); board.groups[0].maxHops = 1;
  board.nodes = ["a", "b"].map((id, i) => ({ id, name: id, project: dir, provider: i ? "codex" : "claude", profileId: id, groupId: "team", x: 0, y: 0 }));
  let host;
  const router = new Router(board, async (id, text) => {
    const delivery = router.deliveries.find(d => d.target === id && d.status === "sent");
    await ledger.delivery(delivery);
    await ledger.record(id, "input_attempt", { delivery_id: delivery.id });
    host.send(id, text);
  });
  host = new SessionHost(router, path.join(dir, "runtime"), root, ledger);
  t.after(async () => { host.dispose(); await ledger.end(); await fs.rm(dir, { recursive: true, force: true }); });
  let codexOutput = ""; host.on("output", (id, data) => { if (id === "b") codexOutput += data; });
  for (const node of board.nodes) await host.start(node, { id: node.id, name: node.name, provider: node.provider, command: process.execPath, args: [path.join(__dirname, "fake-ai.cjs"), "--provider", node.provider], shell: "direct" });
  await wait(() => router.runtime.get("a")?.phase === "ready" && codexOutput.includes("PATCHPORT_FIXTURE"));
  router.ready("b", true); router.connect("a", "b"); host.input("a", "fixture question\r");
  await wait(() => router.deliveries[0]?.status === "completed");
  const report = await ledger.report(dir);
  assert.equal(report.events.filter(e => e.kind === "completed").length, 2);
  assert.ok(report.events.some(e => e.kind === "input_attempt"));
  const managed = host.sessions.get("a");
  const transcript = path.join(dir, `${managed.eventSession}.jsonl`);
  await fs.writeFile(transcript, JSON.stringify({ type: "assistant", sessionId: managed.eventSession, timestamp: new Date().toISOString(), message: { id: "usage-message", model: "fixture", usage: { input_tokens: 10, output_tokens: 3, cache_read_input_tokens: 5, cache_creation_input_tokens: 1 } } }) + "\n");
  const statusPayload = { cwd: dir, session_id: managed.eventSession, transcript_path: transcript, model: { display_name: "fixture" }, cost: { total_cost_usd: 0.12 } };
  await new Promise((resolve, reject) => {
    const child = execFile(path.join(process.env.SystemRoot, "System32/WindowsPowerShell/v1.0/powershell.exe"), ["-NoLogo", "-NoProfile", "-File", path.join(root, "media/statusline.ps1")], { env: { ...process.env, PATCHPORT_ENDPOINT: `http://127.0.0.1:${host.port}/events/a`, PATCHPORT_TOKEN: managed.token } }, error => error ? reject(error) : resolve());
    child.stdin.end(JSON.stringify(statusPayload));
  });
  const metered = await ledger.report(dir);
  assert.equal(metered.summary.metrics.input_tokens.known_sum, 16);
  assert.equal(metered.summary.metrics.cost_usd.known_sum, 0.12);
  assert.equal(metered.summary.metrics.cost_usd.unknown_tasks, 1);
  const outputBefore = codexOutput;
  const original = ledger.delivery.bind(ledger); ledger.delivery = async () => { throw new Error("fixture storage failure"); };
  host.input("a", "second fixture\r"); await wait(() => router.deliveries[1]?.status === "uncertain");
  assert.equal(codexOutput, outputBefore);
  ledger.delivery = original;
});
